---
title: "Introduction"
author: "Daniel Saggau"
date: "5/2/2021"
output: 
  pdf_document:
    number_sections: yes
    fig_caption: yes
citation_package: --biblatex
bibliography: [ref.bib]
nocite: '@*'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# History of Causal Models 

There is no clear consensus on when exactly  strcutal causal modelling originated.
Judea Pearl argues that path analysis, a method proposed by Sewall Wright in the 1920s is the foundation of modern structural causal models.
Sewall Wright, a Statistican and Geneticist, sparked the interest in causal modelling with his path analysis which subsequently was adopted by various other disciplines such as econometrics, psychometrics and sociology.
This path analysis is a structural equation model with one variable per indicator.

Thereafter the Norwegian Economist Trygve Haavelmo (1944) provided a modelling framework for the field of economics in is paper 'The Probability Approach in Econometrics.'
One could argue that this paper provided a new of level of sophistication to the discpline of Econometrics as a distinct field. 
Haavelmo was awarded the Nobel Memorial Prize in Economic Science in 1989 for his work on this issue. 
His work focused on 


Tjalling Koopmans 

## Bayesian Networks 

## SEMs

## SCMs

# References
