---
title: "peters_elements_causal_inference"
author: "Daniel Saggau"
date: "4/22/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Chapter 1 

Probability theory: 

Statistical learning: Capacity measures

Peters et al. (2017) suggest that statistical learning theory has a inverse problem: We have data and want to understand the underlying data generating process and respective underlying structures. 
This true underlying data generating process is unknown.
We cannot observe the true DGP based on observational data, alone.
Learning theory proposes the usage of functional specifications of our model to define the true underlying process that is rule based.
These rules are pivotal because they allow us to specify the behavior of the model when exposed to unseen observation data.
To ensure that this specification works, Peters et al. (2017) suggests that statistical learning theory uses the concept of capacity measures. 
If we have high capacity, our functional specification is very applicable to different dataset.
If we have low capacity, our specification is not representative of many datasets. 

Apart from having the problem of statistical ill posedness (once because the conditional expectation is undefined for values outside of our sample). 
The second problem is that we usually have no full information for a underlying causal model even when having a fully specified observational distribution.

Importance of noise and additional complexity due to causal nature. 
This is called causal learning.

SCM using equations in terms of assignment rather than mathematical equations.
SCM entails a joint distribution over all observables. 

# Time 

Time often necessary but not modelled specifically or well defined. 
Usually relationship envolved dynamical process but it is not always well defined.
Typically hard sciences involve more concise measures of time than social sciences. 

# Relationship mechanical models 

SCM somewhere between mechanisitic model with differential equations and statistical model 

## Chapter 2

SEM vs SCM: SEM: Algebraic equations rather than assignments from CS in SCM

Independent mechanisms

Autonomous modules
in Case example between cause distribution and effect distribution.

Confusion economics + statistics 

Economics = E(Y|do(x)) - claim stats no substance 
Statistics =E(Y|x) - claim SE have no meaning 


