---
title: "A Gentle Introduction into Structural Causal Models"
author: 
- Daniel Saggau $\boldsymbol{\cdot}$ `daniel.saggau@campus.lmu.de`
- Department of Statistics, Ludwig Maximilian University Munich, Germany
date: "April 2021"
output: 
  pdf_document: 

    number_sections: yes
    fig_caption: yes
citation_package: --biblatex
fontsize: 12
linestretch: 1.5
header-includes:
- \usepackage{amsmath}
- \usepackage[makeroom]{cancel}

---

# Abstract 

The interest in understanding relationships of variables beyond co-occurrence has increased the popularity of causal modelling. 
To provide a comprehensive understanding of causal modelling, I introduce two prominent causal model specifications namely (1) Bayesian Causal Networks (BCN) and (2) Structural Causal Models (SCM), focusing on the latter.
Probabilistic specifications such as a BCN cast a model based on conditional probabilities. 
SCMs cast a model based on assignment functions and extend probabilistic models by specifying the data generating process rather than solely utilizing conditional probabilities.
Another difference between these models is their ability to address different queries such as *predictions*, *interventions* and *counterfactuals*.
These queries are part of Pearl's causal hierarchy (2009). 
Pearl matches these queries with their respective actions namely *observing*, *doing* and *imagining*.
I compare the feasibility of addressing these queries and undertaking respective actions for both specifications.
To contextualize SCMs within the field of causality, I also discuss the role of time in causal inference and provide a brief overview of the history of causal modelling.
This paper uses various directed acyclic graphs to highlight the differences in these modelling approaches.
The insights of this paper can be used as a baseline for subsequent research on structural causal models.
