---
title: "A Gentle Introduction into Structural Causal Models"
author: 
- Daniel Saggau $\boldsymbol{\cdot}$ `daniel.saggau@campus.lmu.de`
- Department of Statistics, Ludwig Maximilian University Munich, Germany
date: "April 2021"
output: 
  pdf_document: 
    number_sections: yes
    fig_caption: yes
citation_package: --biblatex
fontsize: 12
linestretch: 1.5
abstract: This paper provides a gentle introduction into causal inference, focusing on structural causal models and respective causal graphs. The first section provides introduces probabilities and will focus on clarifying the difference between observations and causal concepts. The second section discusses the hierachy of causation. The third section dicusses causal graphs. 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction 

In causal research, we are interested in the relationship of our variables outside of a fixed time frame. 
We want to capture relationships that hold outside of an available dataset and results are intended to be generalizable to other time periods^[other datasets].
This paper focuses on structural causal models. 
A lot of research ignores the distinction between structural equation models (SEM) and structural causal models (SCM).
Essentially, the SCM builds on the SEM but there are some important differences.
Firstly, the structural equation model specification stems from disciplines like economics and psychology and is inherently a parametric specification. 
The SCM is a non-parametric specification with additional mechanisms to cast causal graphs.^[Note that we can also create causal graphs with other models like a Bayesian Causal Network Model]

Nevertheless, both models also have a lot in common. 
Structural equation models entail a fully specified set of equations.
Henceforth the model looks at a system perspective of different variables.
These different equations are autonomous which allows us to manipulate equations without modifying the rest of the system. 

Structural Causal Models specify the relationship in functional forms, including latent/unobserved variables.
This is very different to working with conditional probabilities. 
There are two popular schools of thought on how to specify causal mechanisms.

## Baysian Causal Models

Meanwhile structural causal models approach causality via functions.
There are some different inherent to these two approaches.
Conditional probabilities are less stable for causal methods (prediction and intervention).

SCM are able to create counterfactuals, hypothetical knowledge. 
CBN are unable to produce counterfactuals because we fail to specify exogenous variables in a probabilistic model.
CBN only specify observable characteristics. 
SCMs on the other hand specify latent factors too and are built on various distributional assumptions.
In a SCM we may specify the counterfactual distribution from which we can draw counterfactual observations.

 |Method         | CBN |  SCM
|----------------|---------------------------|------------------------|
| Prediction     | $\boldsymbol{\cdot}$ Unstable                                                                                        | $\boldsymbol{\cdot}$ Stable                 
|                | $\boldsymbol{\cdot}$ Volatile to parameter changes                                                                   | $\boldsymbol{\cdot}$ More Natural Specification 
|                | $\boldsymbol{\cdot}$ Re-Estimate entire model                                                                        | $\boldsymbol{\cdot}$ Only estimate $\Delta$ CM
|                |                                                                                                                      | 
| Intervention   | $\boldsymbol{\cdot}$ Costly for Non-Markovian Models                                                                 | $\boldsymbol{\cdot}$ Pot. Cyclic Representation
|                | $\boldsymbol{\cdot}$ Unstable(Nature CP)                                                                             | $\boldsymbol{\cdot}$ Stable(Nature Eq.)
|                | $\boldsymbol{\cdot}$ Only generic estimates($\Delta$ CP)                                                             | $\boldsymbol{\cdot}$ Context specific(Invariance of Eq.)
|                |                                                                                                                      | 
|Counterfactuals | $\boldsymbol{\cdot}$ **Impossible**                                                                                  | $\boldsymbol{\cdot}$ Possible
|                | $\boldsymbol{\cdot}$ no information on latent factors($\epsilon$)                                                    | $\boldsymbol{\cdot}$ Inclusion of latent factors


There are a number of reasons why people are interested in structural causal models.
We can specify exogenous and endogenous variables in our model specification for a SCM. 
When all our variables are fully specified within our model specification (endogenous variables only) we have a deterministic SCM.

Note that while this is very unreasonable because we assume we can explain all exogenous error terms and further we assume that there are no unobserved variables. 
Henceforth, when applying these models, they are seldom fully deterministic. 

```{tikz,fig.cap="Structural Causal Model" ,fig.align="center", echo =F}
\usetikzlibrary{calc}
\usetikzlibrary{positioning}
\usetikzlibrary{arrows}
\usetikzlibrary{calc}
\usetikzlibrary{positioning}
\usetikzlibrary{arrows}
  \begin{tikzpicture}[
    sharp corners=2pt,
    inner sep=6pt,
    node distance=2cm,
    >=latex]
\tikzstyle{my node}=[draw, shape = circle, minimum height=1cm,minimum width=1cm]
\tikzstyle{latent}=[draw, shape = rectangle, minimum height=1cm,minimum width=1cm]
\node[my node, fill=gray!30] (A){A};
\node[latent,left of=A](UA){$U_A$};
\node[my node, fill=gray!30] at ($(A)!0.5!(A)-(0pt,1.5cm)$) (T) {T};
\node[my node,right = 1 cm of T, fill=gray!30](C){C};
\node[latent,left = 1cm of T](UT){$U_T$};
\node[latent,right = 1cm of A](UC){$U_C$};
\draw[->] (A) -- (T);
\draw[->] (UA) -- (A);
\draw[->] (UT) -- (T);
\draw[->] (UC) -- (C);
\draw[->] (A) -- (C);
\draw[->] (T) -- (C);
\end{tikzpicture}
```

# Common Queries in Causal Models

We can apply a number of different queries in these different causal models.
Note that one central advantage of SCMs is that we can cast counterfactuals.
This is unique to structural causal models due to the specification of our distribution of unobserved variables. 

 |Method          | Action |  Example
|-----------------|---------------------------|------------------------|
| Prediction      | Observation/Co-occurrence | What happened...
| Intervention    | Do-manipulation           | What happens if ...
| Counterfactual  | Hypothetical Realities    | What would have happened if...

Table: Pearl - Hierachy of Causation 

## Prediction 

Note that prediction in a causal model and prediction in a machine learning context are not the same thing.
In prediction in causal models we can only modify root nodes.
We are unable to modify the child nodes in causal prediction.
Meanwhile, in a machine learning context we can modify any variable.
We do not have a underlying causal specification, henceforth we are able to modify any variable and undertake prediction. 
One should note that clearly the prediction in causal models has more explanatory power than the prediction in a vanilla-machine learning model. 


## Intervention 

This paper focuses on atomic, policy and off-policy intervention.
Atomic intervention means that we replace a variable with a constant so we replace variable $T$ with constant $t$.
Policy intervention means we replace a variable with a new distribution $\pi$.
Off-policy intervention is an intervention when we only have historical data and no data on the specific intervention. 
Off-policy has gained traction in discplines like reinforced learning.


```{tikz,fig.cap="Atomic Intervention", fig.align="center", echo =F}
\usetikzlibrary{calc}
\usetikzlibrary{positioning}
\usetikzlibrary{arrows}
  \begin{tikzpicture}[
    sharp corners=2pt,
    inner sep=7pt,
    node distance=3cm,
    >=latex]
\tikzstyle{my node}=[draw, shape = circle, minimum height=1cm,minimum width=1cm]
\tikzstyle{latent}=[draw, shape = rectangle, minimum height=1cm,minimum width=1cm]
\node[my node, fill=gray!30] (A){A};
\node[latent,left =1 cm of A](UA){$U_A$};
\node[my node, fill=gray!30] at ($(A)!0.5!(A)-(0pt,1.5 cm)$) (T) {t};
\node[my node,right = 1 cm of T, fill=gray!30](C){C};
\node[latent,right=1 cm of A](UC){$U_C$};
\draw[->] (UA) -- (A);
\draw[->] (UC) -- (C);
\draw[->] (A) -- (C);
\draw[->] (T) -- (C);
\end{tikzpicture}
```


```{tikz,fig.cap="Policy Intervention",  fig.align= "center", echo =F}
\usetikzlibrary{calc}
\usetikzlibrary{positioning}
\usetikzlibrary{arrows}
  \begin{tikzpicture}[
    sharp corners=2pt,
    inner sep=6pt,
    node distance=2cm,
    >=latex]
\tikzstyle{my node}=[draw, shape = circle, minimum height=1cm,minimum width=1cm]
\tikzstyle{latent}=[draw, shape = rectangle, minimum height=1cm,minimum width=1cm]
\node[my node, fill=gray!30] (A){A};
\node[latent,left of=A](UA){$U_A$};
\node[my node, fill=gray!70] at ($(A)!0.5!(A)-(0pt,1.5cm)$) (T) {$T_\pi$};
\node[my node,right = 1 cm of T, fill=gray!30](C){C};
\node[latent,left = 1cm of T](UT){$U_T$};
\node[latent,right = 1cm of A](UC){$U_C$};
\draw[->] (A) -- (T);
\draw[->] (UA) -- (A);
\draw[->] (UT) -- (T);
\draw[->] (UC) -- (C);
\draw[->] (A) -- (C);
\draw[->] (T) -- (C);
\end{tikzpicture}
```



## Counterfactuals

Process is described as follows:

(a) Abduction: Cast probability $P(u)$ as conditional probability $P(u|\epsilon)$ 
(b) Action: Exchange $(X = x)$ 
(c) Prediction: Compute $(Y = y)$

## Causal Graphs 

Causal graphs are graphical models to visualize causal models. 
Causal graphs are based on various different causal models.
A graphical models contains nodes and edges (vertices).
If we are dealing with a causal graph based on a structural causal model, we usually see latent variables.
These latent variables are typically differentiated by either using a different color and/or shape than the nodes in probabilistic models where we only special conditional probabilities.
The absence of a edge between nodes can many different things depending on the underlying model.
Absence in a SCM means that there is no causal relationship.
Absence in a BCN means that there is no conditional probability.  

The most common causal graph is the acyclic directed graph. 
A directed graph is a graph where every edge has a direction.
An un-directed graph has edges but there is no arrow which means that the relationship is unclear.
An acyclic graph is a graph without cycles.
That means that a variable does not cause itself, directly or indirectly.
Given the way we look at time where the relationship between variables is indifferent to time, this representation provides a foundation for graphical models. 

## Criteria 

## D-Seperation 



### Markovian Condition 

#### In Graphical Model 

#### in SCM

### Backdoor criteria 

```{tikz, backdoor, fig.cap ="Backdoor Criterion",  fig.align="center", echo =F}
\usetikzlibrary{calc}
\usetikzlibrary{positioning}
\usetikzlibrary{arrows}
  \begin{tikzpicture}[
    sharp corners=2pt,
    inner sep=7pt,
    node distance=3cm,
    >=latex]
\tikzstyle{my node}=[draw, shape = circle, minimum height=1cm,minimum width=1cm]
\node[my node, fill=gray!30] (A){A};
\node[my node, fill=gray!30] at ($(A)!0.5!(A)-(0pt,1.5cm)$) (T) {T};
\node[my node,right of=T, fill=gray!30](C){C};
\draw[->] (A) -- (T);
\draw[->] (A) -- (C);
\draw[->] (T) -- (C);
\end{tikzpicture}
```



## Causal Mechanisms via Differential Equations 

Differential equations can describe a dynamic system accounting for time.

# Conclusion 

This paper illustrates the versatile nature of structural causal models.
Casting causal mechanisms via a functional specification entails many advantages.
SCMs provide a stable foundation for causal graphs.

# References 



